# .streamlit/secrets.toml
openai_api_key = "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"